Ticket # 147 - About us page layout
UCLA-Creative-Labs/sunshine pull request #166
Opened 2024-11-06 22:35 UTC by lakshman8664

finished page structure using existing components. 
About, Board Member Highlights, and Alumni Recollections sections filled with static data 
Filled Upcoming Events and Past Events (dynamic data) with dummy values temporarily

2024-11-07 01:20 UTC, olliepai requested changes
Pls make the images on the GenericCard be the same height as the text (see Figma).

Note: The home page also uses the GenericCard component so make sure any styling changes do not break the home page.

Everything else looks good!

2024-11-20 04:07 UTC, lakshman8664 commented
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/21d0e733-bda2-4c1b-83d4-480ab05c806f">

Modified the image size in "upcoming events" section. Created a new card for this instead of modifying the GenericCard component.

2025-02-14 06:57 UTC, lakshman8664 commented
new structure for "About Us" page added (since the latest Figma changes)

2025-02-21 03:46 UTC, olliepai approved these changes
looks good

2025-02-21 03:46 UTC, merged